INSERT INTO TIPO_CAMBIO (MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES ('SOLES', 'DOLARES', 0.26);
INSERT INTO TIPO_CAMBIO (MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES ('DOLARES', 'SOLES', 3.92);

INSERT INTO USUARIO (ID, USUARIO, CONTRASENHA) VALUES (1, 'usuario', '$2a$12$nBx0uKbI1F7DJkalgmTez.JSwZu2CbOtMtMvqi7UgS7LAi4vlHn1W');
